# elastalert/config.yaml
es_host: elasticsearch
es_port: 9200

writeback_index: elastalert_status

buffer_time:
  minutes: 15

run_every:
  minutes: 1

alert_time_limit:
  days: 2

rules_folder: /opt/elastalert/rules

# For testing/debugging
verbose: true

